version: "3.8"
services:
  fastapi:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  nodeapi:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    restart: always

  react:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
    restart: always
